package br.salao.salaoapi.domain.enums;

import lombok.Getter;

@Getter
public enum Horarios {
	SETE(0,"SETE"), SETE_QUINZE(1,"SETE_QUINZE"), SETE_TRINTA(2,"SETE_TRINTA"),
	SETE_QUARENTA_E_CINCO(3,"SETE_QUARENTA_E_CINCO"), OITO(4,"OITO"), OITO_QUINZE(5,"OITO_QUINZE"),
	OITO_TRINTA(6,"OITO_TRINTA"), OITO_QUARENTA_E_CINCO(7,"OITO_QUARENTA_E_CINCO"), NOVE(8,"NOVE"),
	NOVE_QUINZE(9,"NOVE_QUINZE"), NOVE_TRINTA(10,"NOVE_TRINTA"),
	NOVE_QUARENTA_E_CINCO(11,"NOVE_QUARENTA_E_CINCO"), DEZ(12,"DEZ"), DEZ_QUINZE(13,"DEZ_QUINZE"),
	DEZ_TRINTA(14,"DEZ_TRINTA"), DEZ_QUARENTA_E_CINCO(15,"DEZ_QUARENTA_E_CINCO"), ONZE(16,"ONZE"),
	ONZE_QUINZE(17,"ONZE_QUINZE"), ONZE_TRINTA(18,"ONZE_TRINTA"),
	ONZE_QUARENTA_E_CINCO(19,"ONZE_QUARENTA_E_CINCO"), DOZE(20,"DOZE"), DOZE_QUINZE(21,"DOZE_QUINZE"),
	DOZE_TRINTA(22,"DOZE_TRINTA"), DOZE_QUARENTA_E_CINCO(23,"DOZE_QUARENTA_E_CINCO"), TREZE(24,"TREZE"),
	TREZE_QUINZE(25,"TREZE_QUINZE"), TREZE_TRINTA(26,"TREZE_TRINTA"),
	TREZE_QUARENTA_E_CINCO(27,"TREZE_QUARENTA_E_CINCO"), QUATORZE(28,"QUATORZE"),
	QUATORZE_QUINZE(29,"QUATORZE_QUINZE"), QUATORZE_TRINTA(30,"QUATORZE_TRINTA"),
	QUATORZE_QUARENTA_E_CINCO(31,"QUATORZE_QUARENTA_E_CINCO"), QUINZE(32,"QUINZE"),
	QUINZE_QUINZE(33,"QUINZE_QUINZE"), QUINZE_TRINTA(34,"QUINZE_TRINTA"),
	QUINZE_QUARENTA_E_CINCO(35,"QUINZE_QUARENTA_E_CINCO"), DEZESSEIS(36,"DEZESSEIS"),
	DEZESSEIS_QUINZE(37,"DEZESSEIS_QUINZE"), DEZESSEIS_TRINTA(38,"DEZESSEIS_TRINTA"),
	DEZESSEIS_QUARENTA_E_CINCO(39,"DEZESSEIS_QUARENTA_E_CINCO"), DEZESSETE(40,"DEZESSETE"),
	DEZESSETE_QUINZE(41,"DEZESSETE_QUINZE"), DEZESSETE_TRINTA(42,"DEZESSETE_TRINTA"),
	DEZESSETE_QUARENTA_E_CINCO(43,"DEZESSETE_QUARENTA_E_CINCO"), DEZOITO(44,"DEZOITO"),
	DEZOITO_QUINZE(45,"DEZOITO_QUINZE"), DEZOITO_TRINTA(46,"DEZOITO_TRINTA"),
	DEZOITO_QUARENTA_E_CINCO(47,"DEZOITO_QUARENTA_E_CINCO"), DEZENOVE(48,"DEZENOVE"),
	DEZENOVE_QUINZE(49,"DEZENOVE_QUINZE"), DEZENOVE_TRINTA(50,"DEZENOVE_TRINTA"),
	DEZENOVE_QUARENTA_E_CINCO(51,"DEZENOVE_QUARENTA_E_CINCO"), VINTE(52,"VINTE");

	private Integer codigo;
	private String descricao;

	private Horarios(Integer codigo, String descricao) {
		this.codigo = codigo;
		this.descricao = descricao;
	}

	public static Horarios toEnum(Integer cod) {
		if(cod == null ) {
			return null;
		}
		
		for(Horarios x : Horarios.values()) {
			if(cod.equals(x.getCodigo())) {
				return x;
			}
		}
		throw new IllegalArgumentException("Horário inválido");
	}

}
